default:
  image: node:16

stages:
  - setup
  - validate
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: setup
  script:
    - echo "INSTALANDO DEPENDENCIAS"
    - npm install --force
    - npm ci --force
  only:
    - develop

check-types:
  stage: validate
  script:
    - echo "VALIDAR TYPESCRIPT"
      - npm run typecheck

check-format:
  stage: validate
  script:
    - echo "VALIDAR PRETTIER"
    - npm run check:format
  only:
    - develop

check-lint:
  stage: validate
  script:
    - echo "VALIDAR ESLINT"
    - npm run check:lint
  only:
    - develop

test-coverage:
  stage: test
  script:
    - echo "VALIDAR TEST"
    - npm install
    - npm run test:unit:coverage

build-dist:
  stage: build
  script:
    - echo "GENERANDO BUILD"
    - npm run build
  only:
    - develop

build-dev-image:
  stage: build
  image: docker:20.10.10
  services:
    - docker:20.10.10-dind
  script:
    - echo "CREANDO IMAGEN"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image rm --force $CI_REGISTRY/$IMAGE_TAG
    - docker build --no-cache -t $CI_REGISTRY/$IMAGE_TAG -f ./docker/Dockerfile .
    - docker push $CI_REGISTRY/$IMAGE_TAG
  only:
    - develop

deploy-dev-image:
  stage: deploy
  image: ubuntu:22.04
  script:
    - echo "DESPLEGANDO"
    - apt update
    - apt install -y curl
    - curl $REDEPLOY_WEBHOOK_URL
  only:
    - develop
